# Generated by Django 4.2.6 on 2023-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hackathon_participant",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
