# Generated by Django 4.1.13 on 2023-11-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_event_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="reg_deadline",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
