# Generated by Django 4.1.13 on 2023-11-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="avatar",
            field=models.ImageField(default="default1.png", upload_to=""),
        ),
    ]
