# Generated by Django 4.1.13 on 2023-12-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_userpoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posts",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
