# Generated by Django 4.1.13 on 2024-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_event_slug_posts_slug_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="avatar",
            field=models.ImageField(default="default1.png", upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="avatars/"),
        ),
    ]
