# Generated by Django 4.1.13 on 2024-01-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_event_avatar_alter_user_avatar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
